apiVersion: v1
kind: Pod
metadata:
  name: simple
spec:
  containers:
  - image: dil001/haproxy-arm64:0.3
    imagePullPolicy: Always
    name: haproxy
    command:
    - /usr/sbin/haproxy
    args:
    - -db
    - -f
    - /etc/haproxy/haproxy.cfg
    ports:
    - containerPort: 80
